export async function GET(request) {
  // Define expected authentication headers
  //edit Rahul Singh

  // Extract headers from the request
  const clientKey = request.headers.get("clientkey");
  const propertyKey = request.headers.get("propertykey");
  const authorization = request.headers.get("authorization");

  // Validate the headers
  if (
    clientKey !== process.env.CLIENT_KEY ||
    propertyKey !== process.env.PROPERTY_KEY ||
    authorization !== process.env.AUTHORIZATION
  ) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }

  // Your API data if authentication succeeds
  const data = [
    {
      id: "67115d6acf1ac4d473030fc3",
      tags: [""],
      title_hn:
        "VIDEO : कमलेश फाइटर गैंग के शातिर शानू के घर पुलिस ने मुनादी कराई",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/18/1T1vAFO.m3u8",
      is_native_player: true,
      category: {
        _id: "61ceb089a069cc26f724c8a9",
        description: "Short Videos",
        full_slug: "short-videos",
        is_featured: "no",
        parent_id: "0",
        slug: "short-videos",
        status: "enable",
        title: "Short Videos",
        title_hn: "शॉर्ट वीडियो",
      },
      created_at: "2024-10-18 00:24:34",
      updated_at: "2024-10-18 00:24:34",
      slug: "video-kamalsha-faitara-gaga-ka-shatara-shana-ka-ghara-palsa-na-manatha-karaii",
      full_slug:
        "video-shots/short-videos/video-kamalsha-faitara-gaga-ka-shatara-shana-ka-ghara-palsa-na-manatha-karaii",
    },
    {
      id: "67115b53e9c44e14840929a3",
      tags: [""],
      title_hn:
        "VIDEO : मैं जिंदा नहीं छोड़ूंगा..., फावड़े लेकर सड़क पर दौड़ा नेपाली युवक, पांच लोगों पर हमला; थाने पर भीड़ का हंगामा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/18/1T1vun9.m3u8",
      is_native_player: true,
      category: {
        _id: "61ceb089a069cc26f724c8a9",
        description: "Short Videos",
        full_slug: "short-videos",
        is_featured: "no",
        parent_id: "0",
        slug: "short-videos",
        status: "enable",
        title: "Short Videos",
        title_hn: "शॉर्ट वीडियो",
      },
      created_at: "2024-10-18 00:15:39",
      updated_at: "2024-10-18 00:15:39",
      slug: "video-youth-created-ruckus-ran-on-road-with-knife-attacked-three-four-people-injured-police-arrived",
      full_slug:
        "video-shots/short-videos/video-youth-created-ruckus-ran-on-road-with-knife-attacked-three-four-people-injured-police-arrived",
    },
    {
      id: "67115a40a0e1fd9415021767",
      tags: [
        "india news",
        "national",
        "vinesh phogat",
        "brij bhushan sharan singh",
        "priyanka gandhi",
        "brij bhushan priyanka gandhi",
        "priyanka gandhi news",
        "brij bhushan",
        "how brij bhushan sharan singh",
        "priyanka gandhi vadra",
        "brij bhushan sharan singh fir",
        "brij bhushan singh interview",
      ],
      title_hn:
        "Wayanad Bye Election: Brij Bhushan Singh के बयान के बयान से मची खलबली। Vinesh Phogat। Priyanka Gandhi",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/Uv268XN3HBc?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-18 00:11:04",
      updated_at: "2024-10-18 00:11:04",
      slug: "wayanad-bye-election-brij-bhushan-singh-s-statement-created-a-stir-vinesh-phogat-priyanka-gandhi-2024-10-18",
      full_slug:
        "video/india-news/wayanad-bye-election-brij-bhushan-singh-s-statement-created-a-stir-vinesh-phogat-priyanka-gandhi-2024-10-18",
    },
    {
      id: "671150cb464f0727a4070361",
      tags: [
        "city & states",
        "uttar pradesh",
        "bahraich",
        "encounter",
        "accused",
        "ram gopal mishra",
        "police",
        "stf",
        "up police",
        "bahraich violence",
        "viral video",
      ],
      title_hn:
        'Bahraich Encounter: गोली लगते ही बोले आरोपी, "गलती हो गई माफी दे दो" देखें एनकाउंटर की पूरी कहानी',
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/XpwPmfKDZ1A?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 23:30:43",
      updated_at: "2024-10-17 23:30:43",
      slug: "bahraich-encounter-as-soon-as-he-was-shot-the-accused-said-i-made-a-mistake-please-forgive-me-2024-10-17",
      full_slug:
        "video/uttar-pradesh/bahraich-encounter-as-soon-as-he-was-shot-the-accused-said-i-made-a-mistake-please-forgive-me-2024-10-17",
    },
    {
      id: "67114f62193fcf9624093263",
      tags: [""],
      title_hn:
        "VIDEO : सैलून संचालक ने युवती से की छेड़छाड़, लोगों ने आरोपी को पीटा, की तोड़फोड़",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1uDGv.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 23:24:42",
      updated_at: "2024-10-17 23:24:42",
      slug: "video-salon-owner-molested-a-girl-people-beat-up-accused-and-vandalised-the-place",
      full_slug:
        "video/dehradun/video-salon-owner-molested-a-girl-people-beat-up-accused-and-vandalised-the-place",
    },
    {
      id: "67114da4b38b1cd6ac02ab4c",
      tags: [
        "world",
        "national",
        "yahya sinwar",
        "hamas chief yahya sinwar",
        "yahya sinwar death",
        "hamas leader yahya sinwar",
        "hamas yahya sinwar",
        "yahya sinwar hamas leader",
        "yahya sinwar killed",
        "yahya sinwar news",
        "yahya sinwar hamas",
        "hamas chief yahya sinwar dead",
      ],
      title_hn:
        "Isreal Killed Hamas Chief Yahya Sinwar:इस्राइल ने हमास चीफ के उड़ाए चिथड़े - चिथड़े| Hezbollah। IDF",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/JhSgl2eMYrA?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "569debbd733ffecb28d19536",
        description: "World",
        full_slug: "world",
        is_featured: "yes",
        parent_id: "569debbd733ffecb28d19536",
        slug: "world",
        status: "enable",
        title: "World",
        title_hn: "दुनिया",
      },
      created_at: "2024-10-17 23:17:16",
      updated_at: "2024-10-17 23:17:16",
      slug: "isreal-killed-hamas-chief-yahya-sinwar-israel-killed-hamas-chief-hezbollah-idf-2024-10-17",
      full_slug:
        "video/world/isreal-killed-hamas-chief-yahya-sinwar-israel-killed-hamas-chief-hezbollah-idf-2024-10-17",
    },
    {
      id: "67114ccc58d831ceb9037d69",
      tags: [""],
      title_hn:
        "VIDEO : दिल्ली में कई इलाकों में गंभीर श्रेणी में दर्ज हुआ एक्यूआई",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1pnMJ.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 23:13:40",
      updated_at: "2024-10-17 23:13:40",
      slug: "video-aqi-recorded-in-severe-category-in-many-areas-of-delhi",
      full_slug:
        "video/delhi/video-aqi-recorded-in-severe-category-in-many-areas-of-delhi",
    },
    {
      id: "6711497bd4ef22b58809d385",
      tags: [""],
      title_hn:
        "VIDEO : बहराइच कांड: मृतक रामगोपाल की पत्नी ने की ये अपील, सोशल मीडिया पर जारी किया वीडियो",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1uhEA.m3u8",
      is_native_player: true,
      category: {
        _id: "61ceb089a069cc26f724c8a9",
        description: "Short Videos",
        full_slug: "short-videos",
        is_featured: "no",
        parent_id: "0",
        slug: "short-videos",
        status: "enable",
        title: "Short Videos",
        title_hn: "शॉर्ट वीडियो",
      },
      created_at: "2024-10-17 22:59:31",
      updated_at: "2024-10-17 22:59:31",
      slug: "video-bharaica-kada-mataka-ramagapal-ka-patana-na-ka-ya-apal-sashal-madaya-para-jara-kaya-vadaya",
      full_slug:
        "video-shots/short-videos/video-bharaica-kada-mataka-ramagapal-ka-patana-na-ka-ya-apal-sashal-madaya-para-jara-kaya-vadaya",
    },
    {
      id: "671147099162d7dd1b090204",
      tags: [""],
      title_hn:
        "VIDEO : शिवपुर में भरत-मिलाप में उमड़े लोग, आकर्षक झांकियों ने बांधा समां, भक्ति से सराबोर हुआ पूरा क्षेत्र",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1tVJL.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 22:49:05",
      updated_at: "2024-10-17 22:49:05",
      slug: "video-people-gathered-in-bharat-milap-attractive-tableaux-created-buzz-entire-area-drenched-devotion",
      full_slug:
        "video/uttar-pradesh/varanasi/video-people-gathered-in-bharat-milap-attractive-tableaux-created-buzz-entire-area-drenched-devotion",
    },
    {
      id: "671142ad90e1a08a4109498a",
      tags: [""],
      title_hn:
        "VIDEO : काशी पहुंचे तेज गेंदबाज मुनाफ पटेल, बोले- गंजारी बनने के बाद पूर्वांचल क्रिकेट का हब बनेगा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1tiRh.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 22:30:29",
      updated_at: "2024-10-17 22:30:29",
      slug: "video-fast-bowler-munaf-patel-reached-kashi-said-after-becoming-ganjari-purvanchal-become-hub-of-cricket",
      full_slug:
        "video/uttar-pradesh/varanasi/video-fast-bowler-munaf-patel-reached-kashi-said-after-becoming-ganjari-purvanchal-become-hub-of-cricket",
    },
    {
      id: "67113e69ffc56235bb0e5258",
      tags: [""],
      title_hn:
        "VIDEO : Shamli: किसान ने अपनी गर्दन पर मारा ब्लेड, बोला- लेकर रहूंगा गन्ने का भुगतान",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1txNs.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 22:12:17",
      updated_at: "2024-10-17 22:12:17",
      slug: "video-shamli-the-farmer-hit-the-blade-on-his-neck-said-i-will-take-the-payment-for-sugarcane",
      full_slug:
        "video/uttar-pradesh/shamli/video-shamli-the-farmer-hit-the-blade-on-his-neck-said-i-will-take-the-payment-for-sugarcane",
    },
    {
      id: "671136ce7bba57325505e9e5",
      tags: [""],
      title_hn:
        "VIDEO : अलीगढ़ के श्री उदयसिंह जैन कन्या इंटर कॉलेज में लगी बाल विज्ञान प्रदर्शनी",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1t1pE.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:39:50",
      updated_at: "2024-10-17 21:39:50",
      slug: "video-algaugdhha-ka-shara-uthayasaha-jana-kanaya-itara-kalja-ma-lga-bl-vajaniana-paratharashana",
      full_slug:
        "video/uttar-pradesh/aligarh/video-algaugdhha-ka-shara-uthayasaha-jana-kanaya-itara-kalja-ma-lga-bl-vajaniana-paratharashana",
    },
    {
      id: "671136c408e01d621204829e",
      tags: [""],
      title_hn:
        "VIDEO : केडीए ने चार अवैध बेसमेंट सील कर दिए, पुलिस भी रही मौजूद",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1t3Cl.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:39:40",
      updated_at: "2024-10-17 21:39:40",
      slug: "video-kadae-na-cara-avathha-bsamata-sal-kara-thae-palsa-bha-raha-majatha",
      full_slug:
        "video/uttar-pradesh/kanpur/video-kadae-na-cara-avathha-bsamata-sal-kara-thae-palsa-bha-raha-majatha",
    },
    {
      id: "6711344a1c9af5f6650c1365",
      tags: ["short videos", "chandigarh"],
      title_hn:
        "VIDEO : जिंदगी से खिलवाड़, चंडीगढ़ में सीटीयू की बस से लटका रहा युवक, चालक ने दौड़ा दी बस",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sS1o.m3u8",
      is_native_player: true,
      category: {
        _id: "61ceb089a069cc26f724c8a9",
        description: "Short Videos",
        full_slug: "short-videos",
        is_featured: "no",
        parent_id: "0",
        slug: "short-videos",
        status: "enable",
        title: "Short Videos",
        title_hn: "शॉर्ट वीडियो",
      },
      created_at: "2024-10-17 21:29:06",
      updated_at: "2024-10-17 22:30:00",
      slug: "video-jathaga-sa-khalvaugdha-cadagaugdhha-ma-sataya-ka-bsa-sa-ltaka-raha-vayakata-calka-na-thaugdha-tha-bsa",
      full_slug:
        "video-shots/short-videos/video-jathaga-sa-khalvaugdha-cadagaugdhha-ma-sataya-ka-bsa-sa-ltaka-raha-vayakata-calka-na-thaugdha-tha-bsa",
    },
    {
      id: "6711329995a08970a901a98e",
      tags: [""],
      title_hn:
        "VIDEO : युवक ने मचाया तांडव, फरसा लेकर सड़क पर दौड़ा, चार लोगों पर किया वार, घायल; तनाव के बाद फोर्स तैनात",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sMcu.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:21:53",
      updated_at: "2024-10-17 21:21:53",
      slug: "video-youth-created-ruckus-ran-on-road-with-knife-attacked-three-four-people-injured-police-arrived",
      full_slug:
        "video/uttar-pradesh/varanasi/video-youth-created-ruckus-ran-on-road-with-knife-attacked-three-four-people-injured-police-arrived",
    },
    {
      id: "67113207690b573be103beb8",
      tags: [
        "india news",
        "national",
        "jharkhand election 2024",
        "jharkhand election news",
        "jharkhand election",
        "jharkhand election date",
        "jharkhand assembly election 2024",
        "jharkhand news",
        "jharkhand",
        "jharkhand election date 2024",
        "jharkhand elections",
        "jharkhand chunav 2024",
      ],
      title_hn:
        "Jharkhand Election 2024:झारखंड में बढ़ीं NDA की मुश्किलें? सीट बंटवारे पर आजसू का खेल!",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/VCQ9TsxOY2k?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 21:19:27",
      updated_at: "2024-10-17 21:19:27",
      slug: "jharkhand-election-2024-nda-s-problems-increased-in-jharkhand-ajsu-s-game-on-seat-sharing-2024-10-17",
      full_slug:
        "video/india-news/jharkhand-election-2024-nda-s-problems-increased-in-jharkhand-ajsu-s-game-on-seat-sharing-2024-10-17",
    },
    {
      id: "67112e5f20c4be0f3e0daaf5",
      tags: [""],
      title_hn:
        "VIDEO : टीबीएम आजाद ने स्वदेशी काटन मिल से ट्रांसपोर्ट नगर तक पूरा किया टनल निर्माण कार्य",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1ste3.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:03:51",
      updated_at: "2024-10-17 21:03:51",
      slug: "video-tabema-aajatha-na-savathasha-katana-mal-sa-tarasaparata-nagara-taka-para-kaya-tanal-naramanae-karaya",
      full_slug:
        "video/uttar-pradesh/kanpur/video-tabema-aajatha-na-savathasha-katana-mal-sa-tarasaparata-nagara-taka-para-kaya-tanal-naramanae-karaya",
    },
    {
      id: "67112e1342cbf3da280c1605",
      tags: [""],
      title_hn:
        "VIDEO : पंजाब के व्यक्ति की अमेरिका में मौत, 25 लाख कर्ज लेकर कमाने विदेश गया था अमनदीप",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sqxC.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:02:35",
      updated_at: "2024-10-17 21:02:35",
      slug: "video-pajab-ka-vayakata-ka-amaraka-ma-mata-25-lkha-karaja-lkara-kamana-vathasha-gaya-tha-amanathapa",
      full_slug:
        "video/punjab/chandigarh-punjab/video-pajab-ka-vayakata-ka-amaraka-ma-mata-25-lkha-karaja-lkara-kamana-vathasha-gaya-tha-amanathapa",
    },
    {
      id: "67112def73800c2af80e4d43",
      tags: [""],
      title_hn:
        "VIDEO : पठानकोट के अमनदीप की अमेरिका में मौत, परिवार पर टूटा दुखों का पहाड़",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1srK10.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:01:59",
      updated_at: "2024-10-17 21:01:59",
      slug: "video-pathanakata-ka-amanathapa-ka-amaraka-ma-mata-paravara-para-tata-thakha-ka-pahaugdha",
      full_slug:
        "video/punjab/chandigarh-punjab/video-pathanakata-ka-amanathapa-ka-amaraka-ma-mata-paravara-para-tata-thakha-ka-pahaugdha",
    },
    {
      id: "67112dac069532d1830e3cf5",
      tags: [""],
      title_hn:
        "VIDEO : Shamli: किसान ने अपनी गर्दन पर मारा ब्लेड, खून से लथपथ बोला, क्यों नहीं दे रहे मेरे गन्ने का भुगतान",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sqcl.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:00:52",
      updated_at: "2024-10-17 21:00:52",
      slug: "video-shamli-the-farmer-hit-his-neck-with-a-blade-soaked-in-blood-he-said-why-are-you-not-paying-for-my-sugarcane",
      full_slug:
        "video/uttar-pradesh/shamli/video-shamli-the-farmer-hit-his-neck-with-a-blade-soaked-in-blood-he-said-why-are-you-not-paying-for-my-sugarcane",
    },
    {
      id: "67112d97991e29d1be0b93f3",
      tags: [""],
      title_hn:
        "VIDEO : अंबाला पहुंचे विज, इस बात पर हुआ पारा हाई, बोले- अफसर कमरा छोड़कर चले जाएं",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sqHE.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 21:00:31",
      updated_at: "2024-10-17 21:00:31",
      slug: "video-vij-reached-ambala-the-temperature-got-high-on-this-issue-he-said-officers-should-leave-the-room",
      full_slug:
        "video/haryana/ambala/video-vij-reached-ambala-the-temperature-got-high-on-this-issue-he-said-officers-should-leave-the-room",
    },
    {
      id: "67112cb8b1c89ed9c5089a53",
      tags: [""],
      title_hn:
        "VIDEO : आर्ट फिएस्टा दिवाली बाजार में पंच गव्य मूर्तियां लोगों को खूब भायीं",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1slH3.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:56:48",
      updated_at: "2024-10-17 20:56:48",
      slug: "video-aarata-faesata-thaval-bjara-ma-paca-gavaya-marataya-lga-ka-khab-bhaya",
      full_slug:
        "video/uttar-pradesh/kanpur/video-aarata-faesata-thaval-bjara-ma-paca-gavaya-marataya-lga-ka-khab-bhaya",
    },
    {
      id: "67112b2d1b936b8642092459",
      tags: [""],
      title_hn: "VIDEO : राम नाम की धुन पर झूमे श्रोता, साधु-संत हुए दंडवत",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sglJ.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:50:13",
      updated_at: "2024-10-17 20:50:13",
      slug: "video-rama-nama-ka-thhana-para-jhama-sharata-sathha-sata-hae-thadavata",
      full_slug:
        "video/uttar-pradesh/kanpur/video-rama-nama-ka-thhana-para-jhama-sharata-sathha-sata-hae-thadavata",
    },
    {
      id: "67112ab3534bdb6ce905db48",
      tags: [""],
      title_hn:
        "VIDEO : राजधानी में कांग्रेस का 'दिल्लीवालों आओ, दिल्ली चलाओ' अभियान शुरू, देवेंद्र यादव ने हरी झंडी दिखाकर रवाना की वैन",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1sdpv.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:48:11",
      updated_at: "2024-10-17 20:48:11",
      slug: "video-rajathhana-ma-kagarasa-ka-thallval-aao-thall-calo-abhayana-shanpr-thavathara-yathava-na-hara-jhada-thakhakara-ravana-ka-vana",
      full_slug:
        "video/delhi-ncr/video-rajathhana-ma-kagarasa-ka-thallval-aao-thall-calo-abhayana-shanpr-thavathara-yathava-na-hara-jhada-thakhakara-ravana-ka-vana",
    },
    {
      id: "67112a008b5cd2586a03ef99",
      tags: [
        "india news",
        "national",
        "maharashtra politics",
        "maharashtra",
        "maharashtra political crisis",
        "maharashtra news",
        "maharashtra news live updates",
        "maharashtra politics news",
        "maharastra politics",
        "maharshtra politics",
        "politics",
        "maharashtra politics explained",
      ],
      title_hn:
        "Maharashtra Politics:महाराष्ट्र में कांग्रेस की जमीन पर सपा की नजर , कहीं दोस्ती में न पड़ जाए दरार?",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/6JL28G8CJG8?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:45:12",
      updated_at: "2024-10-17 20:45:12",
      slug: "maharashtra-politics-sp-s-eye-on-congress-s-land-in-maharashtra-may-there-be-a-rift-in-friendship-2024-10-17",
      full_slug:
        "video/india-news/maharashtra-politics-sp-s-eye-on-congress-s-land-in-maharashtra-may-there-be-a-rift-in-friendship-2024-10-17",
    },
    {
      id: "671129a28b9b09553c028117",
      tags: ["india news", "amar ujala", "hindi", "ujjain news"],
      title_hn:
        "Madhya Pradesh News :उज्जैन की बेटी बनी मिस इंडिया, जानिए कौन है निकिता पोरवाल",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/-O4W9CZAjKk?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:43:38",
      updated_at: "2024-10-17 20:43:38",
      slug: "madhya-pradesh-news-ujjain-s-daughter-becomes-miss-india-know-who-is-nikita-porwal-2024-10-17",
      full_slug:
        "video/india-news/madhya-pradesh-news-ujjain-s-daughter-becomes-miss-india-know-who-is-nikita-porwal-2024-10-17",
    },
    {
      id: "67112916cda0723c580bc668",
      tags: [""],
      title_hn:
        "VIDEO : गंगा घाट के सामने नॉनवेज बनाने पर लोगों ने खोखा स्वामी को पीटा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1s56U.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:41:18",
      updated_at: "2024-10-17 20:41:18",
      slug: "video-people-beat-up-the-kiosk-owner-for-making-non-veg-in-front-of-ganga-ghat-in-haridwar",
      full_slug:
        "video/uttarakhand/haridwar/video-people-beat-up-the-kiosk-owner-for-making-non-veg-in-front-of-ganga-ghat-in-haridwar",
    },
    {
      id: "671128c59162d7dd1b0901fb",
      tags: [
        "india news",
        "national",
        "assam train derail",
        "lokmanya tilak express",
        "8 coaches derail",
        "dibalong",
        "assam railways",
        "agartala lokmanya terminal express",
        "agartala lokmanya terminal express derail",
        "train accident",
        "train",
        "indian railways",
      ],
      title_hn:
        "Assam Train Derail: अगरतला-लोकमान्य टर्मिनल एक्सप्रेस के 8 डिब्बे बेपटरी",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/hzmeDlv6vzk?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:39:57",
      updated_at: "2024-10-17 20:39:57",
      slug: "assam-train-derail-8-coaches-of-agartala-lokmanya-terminal-express-derailed-2024-10-17",
      full_slug:
        "video/india-news/assam-train-derail-8-coaches-of-agartala-lokmanya-terminal-express-derailed-2024-10-17",
    },
    {
      id: "671128bc93384daecb02a41c",
      tags: [""],
      title_hn:
        "VIDEO : पुलिस के सामने बार बालाओं ने लगाए ऐसे ठुमके... मच गया हंगामा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1s74F.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:39:48",
      updated_at: "2024-10-17 20:39:48",
      slug: "video-bar-dancer-danced-in-front-of-police-and-when-there-was-an-uproar-in-badaun",
      full_slug:
        "video/uttar-pradesh/bareilly/video-bar-dancer-danced-in-front-of-police-and-when-there-was-an-uproar-in-badaun",
    },
    {
      id: "671127e90002e7148b04de88",
      tags: [
        "india news",
        "national",
        "maharashtra politics",
        "maharashtra",
        "maharashtra political crisis",
        "maharashtra news",
        "maharashtra news live updates",
        "maharashtra politics news",
        "maharastra politics",
        "maharshtra politics",
        "politics",
        "maharashtra politics explained",
      ],
      title_hn:
        "Maharashtra Politics: ओवैसी के गढ़ में अखिलेश यादव की सभा जानें क्या है सपा की चुनावी प्लान!",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/jS9j96F4RZs?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:36:17",
      updated_at: "2024-10-17 20:36:17",
      slug: "maharashtra-politics-akhilesh-yadav-s-meeting-in-owaisi-s-stronghold-know-what-is-sp-s-election-plan-2024-10-17",
      full_slug:
        "video/india-news/maharashtra-politics-akhilesh-yadav-s-meeting-in-owaisi-s-stronghold-know-what-is-sp-s-election-plan-2024-10-17",
    },
    {
      id: "671127a371f7711d3a062d46",
      tags: [""],
      title_hn:
        "VIDEO : थूक जिहाद पर सरकार के समर्थन में बोले पूर्व सीएम हरीश रावत, जानिए क्या कहा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1s1Ng.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:35:07",
      updated_at: "2024-10-17 20:35:07",
      slug: "video-former-cm-harish-rawat-spoke-in-support-of-government-on-thook-jihad",
      full_slug:
        "video/uttarakhand/haridwar/video-former-cm-harish-rawat-spoke-in-support-of-government-on-thook-jihad",
    },
    {
      id: "671126606e4ce062610efc34",
      tags: [
        "india news",
        "chhattisgarh",
        "chhatisgarh news",
        "surajpur",
        "hindi news",
        "crime news",
      ],
      title_hn:
        "Surajpur Case :सूरजपुर केस का आरोपी गिरफ्तार, बताई वारदात के पीछे की वजह",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/ya-nh0HAm_c?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:29:44",
      updated_at: "2024-10-17 20:29:44",
      slug: "surajpur-case-the-accused-of-surajpur-case-has-been-arrested-told-the-reason-behind-the-incident-2024-10-17",
      full_slug:
        "video/india-news/surajpur-case-the-accused-of-surajpur-case-has-been-arrested-told-the-reason-behind-the-incident-2024-10-17",
    },
    {
      id: "67112623853efd202403bf8a",
      tags: ["city & states", "dehradun"],
      title_hn:
        "VIDEO : त्यूणी में हुआ खेल महाकुंभ, पानी को तरसे छात्र, फिर एसडीएम के कहने पर हुई व्यवस्था",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rNwC.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:28:43",
      updated_at: "2024-10-17 20:28:43",
      slug: "video-students-yearned-for-water-during-khel-maha-kumbh-held-in-atal-adarsh-government-inter-college-tiuni",
      full_slug:
        "video/dehradun/video-students-yearned-for-water-during-khel-maha-kumbh-held-in-atal-adarsh-government-inter-college-tiuni",
    },
    {
      id: "671125dcb8a2ec90c50cf676",
      tags: [
        "india news",
        "noida",
        "bihar hooch tragedy",
        "hooch tragedy",
        "bihar police",
        "nitish kumar",
        "बिहार",
        "सीवान",
        "छपरा",
        "जहरीली शराब त्रासदी",
        "बिहार पुलिस",
        "नीतीश कुमार",
      ],
      title_hn:
        "Bihar Hooch Tragedy: सारण-सीवान में जहरीली शराब से अबतक 29 मौतें | Siwan Hooch Tragedy |Saran Hooch",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/CYsdUX2rzNM?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:27:32",
      updated_at: "2024-10-17 20:28:00",
      slug: "bihar-hooch-tragedy-siwan-hooch-tragedy-saran-hooch-tragedy-nitish-kumar-2024-10-17",
      full_slug:
        "video/india-news/bihar-hooch-tragedy-siwan-hooch-tragedy-saran-hooch-tragedy-nitish-kumar-2024-10-17",
    },
    {
      id: "6711246120850cceb6013b55",
      tags: ["india news", "bhopal"],
      title_hn:
        "Bhopal News :दरिंदे सोहेल ने मासूम बच्ची को बनाया हवस का शिकार, फिर हुआ ये|",
      video_type: "aniview",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:21:13",
      updated_at: "2024-10-17 20:21:13",
      slug: "bhopal-news-cruel-sohail-made-an-innocent-girl-a-victim-of-his-lust-then-this-happened-2024-10-17",
      full_slug:
        "video/india-news/bhopal-news-cruel-sohail-made-an-innocent-girl-a-victim-of-his-lust-then-this-happened-2024-10-17",
    },
    {
      id: "671123ceb9c92039920e080e",
      tags: [""],
      title_hn:
        "VIDEO : महिलाओं की शिकायतों को गंभीरता से लें अफसर, महिला आयोग की सदस्य ने सुनीं शिकायतें",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rGeI.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:18:46",
      updated_at: "2024-10-17 20:18:46",
      slug: "video-officers-should-take-womens-complaints-seriously-women-commission-member-heard-the-complaints",
      full_slug:
        "video/uttar-pradesh/rampur/video-officers-should-take-womens-complaints-seriously-women-commission-member-heard-the-complaints",
    },
    {
      id: "6711238c1a5148837e0dd01e",
      tags: [
        "india news",
        "national",
        "jharkhand election 2024",
        "jharkhand election news",
        "jharkhand election",
        "jharkhand election date",
        "jharkhand assembly election 2024",
        "jharkhand news",
        "jharkhand",
        "jharkhand election date 2024",
        "jharkhand elections",
        "jharkhand chunav 2024",
      ],
      title_hn:
        "Jharkhand Election 2024: झारखंड में NDA का बिगड़ा गेम चिराग पासवान की LJP ने किया बड़ा खेल!",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/ea4UILH8w1U?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:17:40",
      updated_at: "2024-10-17 20:17:40",
      slug: "jharkhand-election-2024-nda-s-game-spoiled-in-jharkhand-chirag-paswan-s-ljp-played-a-big-game-2024-10-17",
      full_slug:
        "video/india-news/jharkhand-election-2024-nda-s-game-spoiled-in-jharkhand-chirag-paswan-s-ljp-played-a-big-game-2024-10-17",
    },
    {
      id: "67112340d6e41b9e75071cc5",
      tags: [
        "india news",
        "hindi news",
        "mp politics",
        "congress",
        "mla",
        "congress mla",
      ],
      title_hn:
        "MP NEWS :मध्य प्रदेश में कांग्रेस विधायक ने शराब के नशे में भगवान शिव को लेकर दिया कैसा बयान",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/TQqWtmuy89k?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:16:24",
      updated_at: "2024-10-17 20:16:24",
      slug: "what-statement-did-the-congress-mla-in-madhya-pradesh-give-about-lord-shiva-while-under-the-influence-of-alcoh-2024-10-17",
      full_slug:
        "video/india-news/what-statement-did-the-congress-mla-in-madhya-pradesh-give-about-lord-shiva-while-under-the-influence-of-alcoh-2024-10-17",
    },
    {
      id: "6711231e0f426589770875d3",
      tags: [""],
      title_hn:
        "VIDEO : वाराणसी में 70 दिन बाद यथास्थान हुई भव्य गंगा आरती, देखें वीडियो",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rHkU.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:15:50",
      updated_at: "2024-10-17 20:15:50",
      slug: "video-watch-video-grand-ganga-aarti-held-at-the-same-place-in-varanasi-after-70-days",
      full_slug:
        "video/uttar-pradesh/varanasi/video-watch-video-grand-ganga-aarti-held-at-the-same-place-in-varanasi-after-70-days",
    },
    {
      id: "6711229d41451443b709bca7",
      tags: [""],
      title_hn:
        "VIDEO : मसूरी में धूमधाम से मनाई वाल्मीकि जयंती...झांकियों के साथ निकाली शोभायात्रा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rBHe.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:13:41",
      updated_at: "2024-10-17 20:13:41",
      slug: "video-valmiki-jayanti-celebrated-in-mussoorie-procession-taken-out-with-tableaux",
      full_slug:
        "video/dehradun/video-valmiki-jayanti-celebrated-in-mussoorie-procession-taken-out-with-tableaux",
    },
    {
      id: "6711219cad2a1e48ed0c06b1",
      tags: [""],
      title_hn:
        "VIDEO : रामपुर में पैदल मार्च निकालकर मेडिकल कॉलेज बनाने का उठाया मुद्दा, किया प्रदर्शन",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rCSb.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:09:24",
      updated_at: "2024-10-17 20:09:24",
      slug: "video-raised-the-issue-of-building-a-medical-college-by-taking-out-a-foot-march-in-rampur-and-demonstrated",
      full_slug:
        "video/uttar-pradesh/rampur/video-raised-the-issue-of-building-a-medical-college-by-taking-out-a-foot-march-in-rampur-and-demonstrated",
    },
    {
      id: "6711215586a6a70d9000e938",
      tags: ["india news", "jaipur", "ashok gehlot", "hindi", "politics"],
      title_hn:
        "Rajasthan Politics:उप चुनाव से कांग्रेस ने अपने दिग्गज नेता अशोक गहलोत और सचिन पायलट को क्यों किया दूर?",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/FVxVUlHwX8U?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:08:13",
      updated_at: "2024-10-17 20:08:13",
      slug: "rajasthan-politics-why-did-congress-keep-its-veteran-leaders-ashok-gehlot-and-sachin-pilot-away-from-the-by-e-2024-10-17",
      full_slug:
        "video/india-news/rajasthan-politics-why-did-congress-keep-its-veteran-leaders-ashok-gehlot-and-sachin-pilot-away-from-the-by-e-2024-10-17",
    },
    {
      id: "671120ee59c40a02070a1ec8",
      tags: [""],
      title_hn:
        "VIDEO : हरिद्वार बस अड्डे का निरीक्षण करने पहुंचे डीएम, गंदगी देख लगाई फटकार",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rxac.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:06:30",
      updated_at: "2024-10-17 20:06:30",
      slug: "video-dm-inspect-haridwar-bus-station-reprimanded-after-seeing-the-dirt",
      full_slug:
        "video/uttarakhand/haridwar/video-dm-inspect-haridwar-bus-station-reprimanded-after-seeing-the-dirt",
    },
    {
      id: "671120d4856d098279075e75",
      tags: [""],
      title_hn:
        "VIDEO : गजराैला नगर पालिका में एसडीएम की जांच जारी, कई प्रश्नों का जवाब नहीं दे पाए कर्मी",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rw3V.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 20:06:04",
      updated_at: "2024-10-17 20:06:04",
      slug: "video-sdm-investigation-continues-in-gajraula-nagar-palika-workers-could-not-answer-many-questions",
      full_slug:
        "video/uttar-pradesh/amroha/video-sdm-investigation-continues-in-gajraula-nagar-palika-workers-could-not-answer-many-questions",
    },
    {
      id: "67111fec9f08bb74bf0f7696",
      tags: [
        "india news",
        "national",
        "sarfaraz bahraich encounter",
        "up police encounter",
        "bahraich violence",
        "encounter",
        "bahraich encounter videos",
        "bahraich encounter",
        "bahraich sarfaraz encounter",
        "bahraich encounter news",
      ],
      title_hn:
        "Bahraich Encounter: सरफराज के एनकाउंटर पर एसपी वृंदा शुक्ला का बड़ा खुलासा",
      video_type: "youtube",
      video_url:
        "https://www.youtube.com/embed/PUNywBD-MeY?rel=0&amp;autoplay=1",
      is_native_player: false,
      category: {
        _id: "56a87d4e1126f48f668b4567",
        description: "India News",
        full_slug: "india-news",
        is_featured: "yes",
        parent_id: "56a87d4e1126f48f668b4567",
        slug: "india-news",
        status: "enable",
        title: "India News",
        title_hn: "देश",
      },
      created_at: "2024-10-17 20:02:12",
      updated_at: "2024-10-17 20:02:12",
      slug: "bahraich-encounter-sp-vrinda-shukla-s-big-revelation-on-sarfaraz-s-encounter-2024-10-17",
      full_slug:
        "video/india-news/bahraich-encounter-sp-vrinda-shukla-s-big-revelation-on-sarfaraz-s-encounter-2024-10-17",
    },
    {
      id: "67111eeb3ae772f3590cd10e",
      tags: [""],
      title_hn:
        "VIDEO : वाराणसी में विदेशी नागरिक बना सनातनी, लिथुआनिया के नागरिक हेनरिक्स की आस्था देखें वीडियो",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rpZG.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 19:57:55",
      updated_at: "2024-10-17 19:57:55",
      slug: "video-a-foreigner-became-a-sanatani-in-varanasi-watch-the-video-of-lithuanian-citizen-henriques-faith",
      full_slug:
        "video/uttar-pradesh/varanasi/video-a-foreigner-became-a-sanatani-in-varanasi-watch-the-video-of-lithuanian-citizen-henriques-faith",
    },
    {
      id: "67111eb79dcb8b9cb50bcffc",
      tags: [""],
      title_hn:
        "VIDEO : भाजपा समर्थक बने मुरादाबाद की तीनों समितियों के सभापति और उप सभापति, सहकारी गन्ना समितियों का चुनाव संपन्न",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rrlp.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 19:57:03",
      updated_at: "2024-10-17 19:57:03",
      slug: "video-bjp-supporters-became-the-chairmen-of-all-three-committees-of-moradabad-election-of-cooperative-sugarcane-committees-completed",
      full_slug:
        "video/uttar-pradesh/moradabad/video-bjp-supporters-became-the-chairmen-of-all-three-committees-of-moradabad-election-of-cooperative-sugarcane-committees-completed",
    },
    {
      id: "67111dc1a31553623a094388",
      tags: [""],
      title_hn:
        "VIDEO : अभद्रता करने पर डीआईओएस पर भड़के कर्मचारी, मुरादाबाद में मच गया हंगामा",
      video_type: "auw_video",
      video_url:
        "https://d2570yern32wrv.cloudfront.net/uploaded_videos/hyperlocal_videos/2024/10/17/1T1rmtc.m3u8",
      is_native_player: true,
      category: {
        _id: "569ceb6dfdb34fe5330355ee",
        description: "City and states",
        full_slug: "city-and-states",
        is_featured: "no",
        parent_id: "569ceb6dfdb34fe5330355ee",
        slug: "city-and-states",
        status: "enable",
        title: "City & states",
        title_hn: "शहर और राज्य",
      },
      created_at: "2024-10-17 19:52:57",
      updated_at: "2024-10-17 19:52:57",
      slug: "video-employees-got-angry-at-dios-for-misbehaving-uproar-broke-out-in-moradabad",
      full_slug:
        "video/uttar-pradesh/moradabad/video-employees-got-angry-at-dios-for-misbehaving-uproar-broke-out-in-moradabad",
    },
  ];

  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  });
}
