export async function GET(request) {
  // Define expected authentication headers
  //edit Rahul Singh

  // Extract headers from the request
  const clientKey = request.headers.get("clientkey");
  const propertyKey = request.headers.get("propertykey");
  const authorization = request.headers.get("authorization");

  // Validate the headers
  if (
    clientKey !== process.env.CLIENT_KEY ||
    propertyKey !== process.env.PROPERTY_KEY ||
    authorization !== process.env.AUTHORIZATION
  ) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }

  // Your API data if authentication succeeds
  const data = {
    address: "Tvvyv",
    city: "Ghaziabad",
    dob: "1987-06-28T00:00:00.000Z",
    email: "kailash.karayat@auw.co.in",
    first_name: "Kailash",
    gender: "male",
    last_name: "Karayat",
    mobile_no: "+919899181043",
    occupation: "others",
    occupations_list: [
      { name: "salaried", value: "Salaried" },
      { name: "business_owner", value: "Business Owner" },
      { name: "self_employed", value: "Self Employed" },
      { name: "student", value: "Student" },
      { name: "homemaker", value: "Homemaker" },
      { name: "retired", value: "Retired" },
      { name: "unemployed", value: "Unemployed" },
      { name: "others", value: "Others" },
    ],
    state: "Uttar Pradesh",
    state_list: [
      { name: "Andaman and Nicobar Islands", state_code: "AN" },
      { name: "Andhra Pradesh", state_code: "AD" },
      { name: "Arunachal Pradesh", state_code: "AR" },
      { name: "Assam", state_code: "AS" },
      { name: "Bihar", state_code: "BH" },
      { name: "Chandigarh", state_code: "CH" },
      { name: "Chattisgarh", state_code: "CT" },
      { name: "Dadra and Nagar Haveli", state_code: "DN" },
      { name: "Daman and Diu", state_code: "DD" },
      { name: "Delhi", state_code: "DL" },
      { name: "Goa", state_code: "GA" },
      { name: "Gujarat", state_code: "GJ" },
      { name: "Haryana", state_code: "HR" },
      { name: "Himachal Pradesh", state_code: "HP" },
      { name: "Jammu and Kashmir", state_code: "JK" },
      { name: "Jharkhand", state_code: "JH" },
      { name: "Karnataka", state_code: "KA" },
      { name: "Kerala", state_code: "KL" },
      { name: "Lakshadweep Islands", state_code: "LD" },
      { name: "Madhya Pradesh", state_code: "MP" },
      { name: "Maharashtra", state_code: "MH" },
      { name: "Manipur", state_code: "MA" },
      { name: "Meghalaya", state_code: "ME" },
      { name: "Mizoram", state_code: "MI" },
      { name: "Nagaland", state_code: "NL" },
      { name: "Odisha", state_code: "OR" },
      { name: "Pondicherry", state_code: "PY" },
      { name: "Punjab", state_code: "PB" },
      { name: "Rajasthan", state_code: "RJ" },
      { name: "Tamil Nadu", state_code: "TN" },
      { name: "Telangana", state_code: "TS" },
      { name: "Tripura", state_code: "TR" },
      { name: "Uttar Pradesh", state_code: "UP" },
      { name: "Uttarakhand", state_code: "UT" },
      { name: "West Bengal", state_code: "WB" },
    ],
    story_count: 19,
    subscription: [
      {
        created_at: "2024-09-25T12:00:16+05:30",
        currency: "USD",
        invoice: "invoice/2024/09/25/Auplus202_1STlwPpG.pdf",
        name: "AU-Plus Subscription (Monthly) - International",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 4.99,
        uid: "1STlwPpG",
        valid_from: "2025-09-25T11:56:59+05:30",
        valid_until: "2025-10-25T11:56:59+05:30",
      },
      {
        created_at: "2024-09-25T11:56:59+05:30",
        currency: "USD",
        invoice: "invoice/2024/09/25/Auplus201_1STltx7v.pdf",
        name: "AU-Plus Subscription (Yearly)  - International",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 39,
        uid: "1STltx7v",
        valid_from: "2024-09-25T11:56:59+05:30",
        valid_until: "2025-09-25T11:56:59+05:30",
      },
      {
        created_at: "2024-07-24T16:28:13+05:30",
        currency: "INR",
        invoice: "invoice/2024/07/24/Auplus011_1SwzH73l.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1SwzH73l",
        valid_from: "2028-07-31T12:07:17+05:30",
        valid_until: "2028-07-31T12:07:17+05:30",
      },
      {
        created_at: "2024-07-24T16:24:28+05:30",
        currency: "INR",
        invoice: "invoice/2024/07/24/Auplus010_1SwzDyKM.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1SwzDyKM",
        valid_from: "2028-07-01T12:07:17+05:30",
        valid_until: "2028-07-01T12:07:17+05:30",
      },
      {
        created_at: "2024-07-24T11:56:05+05:30",
        currency: "INR",
        invoice: "invoice/2024/07/24/Auplus008_1SwvrPyC.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1SwvrPyC",
        valid_from: "2028-06-01T12:07:17+05:30",
        valid_until: "2028-06-01T12:07:17+05:30",
      },
      {
        created_at: "2024-06-11T05:14:13+05:30",
        currency: "INR",
        invoice: "invoice/2024/06/11/Auplus006_1SgODwn6.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1SgODwn6",
        valid_from: "2028-05-02T12:07:17+05:30",
        valid_until: "2028-05-02T12:07:17+05:30",
      },
      {
        created_at: "2024-03-12T11:31:39+05:30",
        currency: "INR",
        invoice: "invoice/2024/03/12/Auplus425_1RJVcIRF.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1RJVcIRF",
        valid_from: "2028-04-02T12:07:17+05:30",
        valid_until: "2028-04-02T12:07:17+05:30",
      },
      {
        created_at: "2024-03-12T11:18:20+05:30",
        currency: "INR",
        invoice: "invoice/2024/03/12/Auplus424_1RJUZMB5.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1RJUZMB5",
        valid_from: "2028-03-03T12:07:17+05:30",
        valid_until: "2028-03-03T12:07:17+05:30",
      },
      {
        created_at: "2024-03-12T11:12:34+05:30",
        currency: "INR",
        invoice: "invoice/2024/03/12/Auplus423_1RJUUfhP.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1RJUUfhP",
        valid_from: "2028-02-02T12:07:17+05:30",
        valid_until: "2028-02-02T12:07:17+05:30",
      },
      {
        created_at: "2024-01-05T13:49:01+05:30",
        currency: "INR",
        invoice: "invoice/2024/01/05/Auplus396_1RlFpi104.pdf",
        name: "AU-Plus Subscription (Monthly)",
        payment_type: "recurring",
        subscription_status: "ACTIVE",
        total_price: 69,
        uid: "1RlFpi104",
        valid_from: "2028-01-03T12:07:17+05:30",
        valid_until: "2028-01-03T12:07:17+05:30",
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  });
}
